using System.Collections.Generic;
using System.Linq;

namespace OLOD_DEMO
{
    public class CountryDTO
    {
        public string Name { get; set; }
        public string Iso3 { get; set; }
        public string Iso2 { get; set; }

    }

    public class CountryFinder
    {
        public static CountryDTO FindCountry(string name)
        {
            var all = LoadCountries();

            var found = all.FirstOrDefault(x => x.Iso2.Trim().ToLower() == name.Trim().ToLower());
            if (found != null) return found;

            found = all.FirstOrDefault(x => x.Iso3.Trim().ToLower() == name.Trim().ToLower());
            if (found != null) return found;

            found = all.FirstOrDefault(x => x.Name.Trim().ToLower() == name.Trim().ToLower());
            if (found != null) return found;

            return new CountryDTO();
        }

        public static List<CountryDTO> LoadCountries()
        {
            var c = new List<CountryDTO>
                        {
                            new CountryDTO() {Iso2 = "US", Iso3 = "USA", Name = "United States"},
                            new CountryDTO() {Iso2 = "CA", Iso3 = "CAN", Name = "Canada"},
                            new CountryDTO() {Iso2 = "GE", Iso3 = "GEO", Name = "Abkhazia"},
                            new CountryDTO() {Iso2 = "AF", Iso3 = "AFG", Name = "Afghanistan"},
                            new CountryDTO() {Iso2 = "AX", Iso3 = "ALA", Name = "Aland"},
                            new CountryDTO() {Iso2 = "AL", Iso3 = "ALB", Name = "Albania"},
                            new CountryDTO() {Iso2 = "DZ", Iso3 = "DZA", Name = "Algeria"},
                            new CountryDTO() {Iso2 = "AS", Iso3 = "ASM", Name = "American Samoa"},
                            new CountryDTO() {Iso2 = "AD", Iso3 = "AND", Name = "Andorra"},
                            new CountryDTO() {Iso2 = "AO", Iso3 = "AGO", Name = "Angola"},
                            new CountryDTO() {Iso2 = "AI", Iso3 = "AIA", Name = "Anguilla"},
                            new CountryDTO() {Iso2 = "AG", Iso3 = "ATG", Name = "Antigua and Barbuda"},
                            new CountryDTO() {Iso2 = "AR", Iso3 = "ARG", Name = "Argentina"},
                            new CountryDTO() {Iso2 = "AM", Iso3 = "ARM", Name = "Armenia"},
                            new CountryDTO() {Iso2 = "AW", Iso3 = "ABW", Name = "Aruba"},
                            new CountryDTO() {Iso2 = "AC", Iso3 = "ASC", Name = "Ascension"},
                            new CountryDTO() {Iso2 = "AU", Iso3 = "AUS", Name = "Ashmore and Cartier Islands"},
                            new CountryDTO() {Iso2 = "AU", Iso3 = "AUS", Name = "Australia"},
                            new CountryDTO() {Iso2 = "AQ", Iso3 = "ATA", Name = "Australian Antarctic Territory"},
                            new CountryDTO() {Iso2 = "AT", Iso3 = "AUT", Name = "Austria"},
                            new CountryDTO() {Iso2 = "AZ", Iso3 = "AZE", Name = "Azerbaijan"},
                            new CountryDTO() {Iso2 = "BS", Iso3 = "BHS", Name = "Bahamas, The"},
                            new CountryDTO() {Iso2 = "BH", Iso3 = "BHR", Name = "Bahrain"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Baker Island"},
                            new CountryDTO() {Iso2 = "BD", Iso3 = "BGD", Name = "Bangladesh"},
                            new CountryDTO() {Iso2 = "BB", Iso3 = "BRB", Name = "Barbados"},
                            new CountryDTO() {Iso2 = "BY", Iso3 = "BLR", Name = "Belarus"},
                            new CountryDTO() {Iso2 = "BE", Iso3 = "BEL", Name = "Belgium"},
                            new CountryDTO() {Iso2 = "BZ", Iso3 = "BLZ", Name = "Belize"},
                            new CountryDTO() {Iso2 = "BJ", Iso3 = "BEN", Name = "Benin"},
                            new CountryDTO() {Iso2 = "BM", Iso3 = "BMU", Name = "Bermuda"},
                            new CountryDTO() {Iso2 = "BT", Iso3 = "BTN", Name = "Bhutan"},
                            new CountryDTO() {Iso2 = "BO", Iso3 = "BOL", Name = "Bolivia"},
                            new CountryDTO() {Iso2 = "BA", Iso3 = "BIH", Name = "Bosnia and Herzegovina"},
                            new CountryDTO() {Iso2 = "BW", Iso3 = "BWA", Name = "Botswana"},
                            new CountryDTO() {Iso2 = "BV", Iso3 = "BVT", Name = "Bouvet Island"},
                            new CountryDTO() {Iso2 = "BR", Iso3 = "BRA", Name = "Brazil"},
                            new CountryDTO() {Iso2 = "AQ", Iso3 = "ATA", Name = "British Antarctic Territory"},
                            new CountryDTO() {Iso2 = "IO", Iso3 = "IOT", Name = "British Indian Ocean Territory"},
                            //new CountryDTO() {Iso2 = "", Iso3="", Name="British Sovereign Base Areas"},
                            new CountryDTO() {Iso2 = "VG", Iso3 = "VGB", Name = "British Virgin Islands"},
                            new CountryDTO() {Iso2 = "BN", Iso3 = "BRN", Name = "Brunei"},
                            new CountryDTO() {Iso2 = "BG", Iso3 = "BGR", Name = "Bulgaria"},
                            new CountryDTO() {Iso2 = "BF", Iso3 = "BFA", Name = "Burkina Faso"},
                            new CountryDTO() {Iso2 = "BI", Iso3 = "BDI", Name = "Burundi"},
                            new CountryDTO() {Iso2 = "KH", Iso3 = "KHM", Name = "Cambodia"},
                            new CountryDTO() {Iso2 = "CM", Iso3 = "CMR", Name = "Cameroon"},
                            new CountryDTO() {Iso2 = "CV", Iso3 = "CPV", Name = "Cape Verde"},
                            new CountryDTO() {Iso2 = "KY", Iso3 = "CYM", Name = "Cayman Islands"},
                            new CountryDTO() {Iso2 = "CF", Iso3 = "CAF", Name = "Central African Republic"},
                            new CountryDTO() {Iso2 = "TD", Iso3 = "TCD", Name = "Chad"},
                            new CountryDTO() {Iso2 = "CL", Iso3 = "CHL", Name = "Chile"},
                            new CountryDTO() {Iso2 = "CN", Iso3 = "CHN", Name = "China, People's Republic of"},
                            new CountryDTO() {Iso2 = "TW", Iso3 = "TWN", Name = "China, Republic of (Taiwan)"},
                            new CountryDTO() {Iso2 = "CX", Iso3 = "CXR", Name = "Christmas Island"},
                            new CountryDTO() {Iso2 = "PF", Iso3 = "PYF", Name = "Clipperton Island"},
                            new CountryDTO() {Iso2 = "CC", Iso3 = "CCK", Name = "Cocos (Keeling) Islands"},
                            new CountryDTO() {Iso2 = "CO", Iso3 = "COL", Name = "Colombia"},
                            new CountryDTO() {Iso2 = "KM", Iso3 = "COM", Name = "Comoros"},
                            new CountryDTO() {Iso2 = "CG", Iso3 = "COG", Name = "Congo, (Congo  Brazzaville)"},
                            new CountryDTO() {Iso2 = "CD", Iso3 = "COD", Name = "Congo, (Congo  Kinshasa)"},
                            new CountryDTO() {Iso2 = "CK", Iso3 = "COK", Name = "Cook Islands"},
                            new CountryDTO() {Iso2 = "AU", Iso3 = "AUS", Name = "Coral Sea Islands"},
                            new CountryDTO() {Iso2 = "CR", Iso3 = "CRI", Name = "Costa Rica"},
                            new CountryDTO() {Iso2 = "CI", Iso3 = "CIV", Name = "Cote d'Ivoire (Ivory Coast)"},
                            new CountryDTO() {Iso2 = "HR", Iso3 = "HRV", Name = "Croatia"},
                            new CountryDTO() {Iso2 = "CU", Iso3 = "CUB", Name = "Cuba"},
                            new CountryDTO() {Iso2 = "CY", Iso3 = "CYP", Name = "Cyprus"},
                            new CountryDTO() {Iso2 = "CZ", Iso3 = "CZE", Name = "Czech Republic"},
                            new CountryDTO() {Iso2 = "DK", Iso3 = "DNK", Name = "Denmark"},
                            new CountryDTO() {Iso2 = "DJ", Iso3 = "DJI", Name = "Djibouti"},
                            new CountryDTO() {Iso2 = "DM", Iso3 = "DMA", Name = "Dominica"},
                            new CountryDTO() {Iso2 = "DO", Iso3 = "DOM", Name = "Dominican Republic"},
                            new CountryDTO() {Iso2 = "EC", Iso3 = "ECU", Name = "Ecuador"},
                            new CountryDTO() {Iso2 = "EG", Iso3 = "EGY", Name = "Egypt"},
                            new CountryDTO() {Iso2 = "SV", Iso3 = "SLV", Name = "El Salvador"},
                            new CountryDTO() {Iso2 = "GQ", Iso3 = "GNQ", Name = "Equatorial Guinea"},
                            new CountryDTO() {Iso2 = "ER", Iso3 = "ERI", Name = "Eritrea"},
                            new CountryDTO() {Iso2 = "EE", Iso3 = "EST", Name = "Estonia"},
                            new CountryDTO() {Iso2 = "ET", Iso3 = "ETH", Name = "Ethiopia"},
                            new CountryDTO() {Iso2 = "FK", Iso3 = "FLK", Name = "Falkland Islands (Islas Malvinas)"},
                            new CountryDTO() {Iso2 = "FO", Iso3 = "FRO", Name = "Faroe Islands"},
                            new CountryDTO() {Iso2 = "FJ", Iso3 = "FJI", Name = "Fiji"},
                            new CountryDTO() {Iso2 = "FI", Iso3 = "FIN", Name = "Finland"},
                            new CountryDTO() {Iso2 = "FR", Iso3 = "FRA", Name = "France"},
                            new CountryDTO() {Iso2 = "GF", Iso3 = "GUF", Name = "French Guiana"},
                            new CountryDTO() {Iso2 = "PF", Iso3 = "PYF", Name = "French Polynesia"},
                            new CountryDTO() {Iso2 = "TF", Iso3 = "ATF", Name = "French Southern and Antarctic Lands"},
                            new CountryDTO() {Iso2 = "GA", Iso3 = "GAB", Name = "Gabon"},
                            new CountryDTO() {Iso2 = "GM", Iso3 = "GMB", Name = "Gambia, The"},
                            new CountryDTO() {Iso2 = "GE", Iso3 = "GEO", Name = "Georgia"},
                            new CountryDTO() {Iso2 = "DE", Iso3 = "DEU", Name = "Germany"},
                            new CountryDTO() {Iso2 = "GH", Iso3 = "GHA", Name = "Ghana"},
                            new CountryDTO() {Iso2 = "GI", Iso3 = "GIB", Name = "Gibraltar"},
                            new CountryDTO() {Iso2 = "GR", Iso3 = "GRC", Name = "Greece"},
                            new CountryDTO() {Iso2 = "GL", Iso3 = "GRL", Name = "Greenland"},
                            new CountryDTO() {Iso2 = "GD", Iso3 = "GRD", Name = "Grenada"},
                            new CountryDTO() {Iso2 = "GP", Iso3 = "GLP", Name = "Guadeloupe"},
                            new CountryDTO() {Iso2 = "GU", Iso3 = "GUM", Name = "Guam"},
                            new CountryDTO() {Iso2 = "GT", Iso3 = "GTM", Name = "Guatemala"},
                            new CountryDTO() {Iso2 = "GG", Iso3 = "GGY", Name = "Guernsey"},
                            new CountryDTO() {Iso2 = "GN", Iso3 = "GIN", Name = "Guinea"},
                            new CountryDTO() {Iso2 = "GW", Iso3 = "GNB", Name = "Guinea-Bissau"},
                            new CountryDTO() {Iso2 = "GY", Iso3 = "GUY", Name = "Guyana"},
                            new CountryDTO() {Iso2 = "HT", Iso3 = "HTI", Name = "Haiti"},
                            new CountryDTO() {Iso2 = "HM", Iso3 = "HMD", Name = "Heard Island and McDonald Islands"},
                            new CountryDTO() {Iso2 = "HN", Iso3 = "HND", Name = "Honduras"},
                            new CountryDTO() {Iso2 = "HK", Iso3 = "HKG", Name = "Hong Kong"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Howland Island"},
                            new CountryDTO() {Iso2 = "HU", Iso3 = "HUN", Name = "Hungary"},
                            new CountryDTO() {Iso2 = "IS", Iso3 = "ISL", Name = "Iceland"},
                            new CountryDTO() {Iso2 = "IN", Iso3 = "IND", Name = "India"},
                            new CountryDTO() {Iso2 = "ID", Iso3 = "IDN", Name = "Indonesia"},
                            new CountryDTO() {Iso2 = "IR", Iso3 = "IRN", Name = "Iran"},
                            new CountryDTO() {Iso2 = "IQ", Iso3 = "IRQ", Name = "Iraq"},
                            new CountryDTO() {Iso2 = "IE", Iso3 = "IRL", Name = "Ireland"},
                            new CountryDTO() {Iso2 = "IM", Iso3 = "IMN", Name = "Isle of Man"},
                            new CountryDTO() {Iso2 = "IL", Iso3 = "ISR", Name = "Israel"},
                            new CountryDTO() {Iso2 = "IT", Iso3 = "ITA", Name = "Italy"},
                            new CountryDTO() {Iso2 = "JM", Iso3 = "JAM", Name = "Jamaica"},
                            new CountryDTO() {Iso2 = "JP", Iso3 = "JPN", Name = "Japan"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Jarvis Island"},
                            new CountryDTO() {Iso2 = "JE", Iso3 = "JEY", Name = "Jersey"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Johnston Atoll"},
                            new CountryDTO() {Iso2 = "JO", Iso3 = "JOR", Name = "Jordan"},
                            new CountryDTO() {Iso2 = "KZ", Iso3 = "KAZ", Name = "Kazakhstan"},
                            new CountryDTO() {Iso2 = "KE", Iso3 = "KEN", Name = "Kenya"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Kingman Reef"},
                            new CountryDTO() {Iso2 = "KI", Iso3 = "KIR", Name = "Kiribati"},
                            new CountryDTO() {Iso2 = "KP", Iso3 = "PRK", Name = "Korea, North"},
                            new CountryDTO() {Iso2 = "KR", Iso3 = "KOR", Name = "Korea, South"},
                            new CountryDTO() {Iso2 = "KW", Iso3 = "KWT", Name = "Kuwait"},
                            new CountryDTO() {Iso2 = "KG", Iso3 = "KGZ", Name = "Kyrgyzstan"},
                            new CountryDTO() {Iso2 = "LA", Iso3 = "LAO", Name = "Laos"},
                            new CountryDTO() {Iso2 = "LV", Iso3 = "LVA", Name = "Latvia"},
                            new CountryDTO() {Iso2 = "LB", Iso3 = "LBN", Name = "Lebanon"},
                            new CountryDTO() {Iso2 = "LS", Iso3 = "LSO", Name = "Lesotho"},
                            new CountryDTO() {Iso2 = "LR", Iso3 = "LBR", Name = "Liberia"},
                            new CountryDTO() {Iso2 = "LY", Iso3 = "LBY", Name = "Libya"},
                            new CountryDTO() {Iso2 = "LI", Iso3 = "LIE", Name = "Liechtenstein"},
                            new CountryDTO() {Iso2 = "LT", Iso3 = "LTU", Name = "Lithuania"},
                            new CountryDTO() {Iso2 = "LU", Iso3 = "LUX", Name = "Luxembourg"},
                            new CountryDTO() {Iso2 = "MO", Iso3 = "MAC", Name = "Macau"},
                            new CountryDTO() {Iso2 = "MK", Iso3 = "MKD", Name = "Macedonia"},
                            new CountryDTO() {Iso2 = "MG", Iso3 = "MDG", Name = "Madagascar"},
                            new CountryDTO() {Iso2 = "MW", Iso3 = "MWI", Name = "Malawi"},
                            new CountryDTO() {Iso2 = "MY", Iso3 = "MYS", Name = "Malaysia"},
                            new CountryDTO() {Iso2 = "MV", Iso3 = "MDV", Name = "Maldives"},
                            new CountryDTO() {Iso2 = "ML", Iso3 = "MLI", Name = "Mali"},
                            new CountryDTO() {Iso2 = "MT", Iso3 = "MLT", Name = "Malta"},
                            new CountryDTO() {Iso2 = "MH", Iso3 = "MHL", Name = "Marshall Islands"},
                            new CountryDTO() {Iso2 = "MQ", Iso3 = "MTQ", Name = "Martinique"},
                            new CountryDTO() {Iso2 = "MR", Iso3 = "MRT", Name = "Mauritania"},
                            new CountryDTO() {Iso2 = "MU", Iso3 = "MUS", Name = "Mauritius"},
                            new CountryDTO() {Iso2 = "YT", Iso3 = "MYT", Name = "Mayotte"},
                            new CountryDTO() {Iso2 = "MX", Iso3 = "MEX", Name = "Mexico"},
                            new CountryDTO() {Iso2 = "FM", Iso3 = "FSM", Name = "Micronesia"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Midway Islands"},
                            new CountryDTO() {Iso2 = "MD", Iso3 = "MDA", Name = "Moldova"},
                            new CountryDTO() {Iso2 = "MC", Iso3 = "MCO", Name = "Monaco"},
                            new CountryDTO() {Iso2 = "MN", Iso3 = "MNG", Name = "Mongolia"},
                            new CountryDTO() {Iso2 = "ME", Iso3 = "MNE", Name = "Montenegro"},
                            new CountryDTO() {Iso2 = "MS", Iso3 = "MSR", Name = "Montserrat"},
                            new CountryDTO() {Iso2 = "MA", Iso3 = "MAR", Name = "Morocco"},
                            new CountryDTO() {Iso2 = "MZ", Iso3 = "MOZ", Name = "Mozambique"},
                            new CountryDTO() {Iso2 = "MM", Iso3 = "MMR", Name = "Myanmar (Burma)"},
                            new CountryDTO() {Iso2 = "AZ", Iso3 = "AZE", Name = "Nagorno-Karabakh"},
                            new CountryDTO() {Iso2 = "NA", Iso3 = "NAM", Name = "Namibia"},
                            new CountryDTO() {Iso2 = "NR", Iso3 = "NRU", Name = "Nauru"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Navassa Island"},
                            new CountryDTO() {Iso2 = "NP", Iso3 = "NPL", Name = "Nepal"},
                            new CountryDTO() {Iso2 = "NL", Iso3 = "NLD", Name = "Netherlands"},
                            new CountryDTO() {Iso2 = "AN", Iso3 = "ANT", Name = "Netherlands Antilles"},
                            new CountryDTO() {Iso2 = "NC", Iso3 = "NCL", Name = "New Caledonia"},
                            new CountryDTO() {Iso2 = "NZ", Iso3 = "NZL", Name = "New Zealand"},
                            new CountryDTO() {Iso2 = "NI", Iso3 = "NIC", Name = "Nicaragua"},
                            new CountryDTO() {Iso2 = "NE", Iso3 = "NER", Name = "Niger"},
                            new CountryDTO() {Iso2 = "NG", Iso3 = "NGA", Name = "Nigeria"},
                            new CountryDTO() {Iso2 = "NU", Iso3 = "NIU", Name = "Niue"},
                            new CountryDTO() {Iso2 = "NF", Iso3 = "NFK", Name = "Norfolk Island"},
                            new CountryDTO() {Iso2 = "CY", Iso3 = "CYP", Name = "Northern Cyprus"},
                            new CountryDTO() {Iso2 = "MP", Iso3 = "MNP", Name = "Northern Mariana Islands"},
                            new CountryDTO() {Iso2 = "NO", Iso3 = "NOR", Name = "Norway"},
                            new CountryDTO() {Iso2 = "OM", Iso3 = "OMN", Name = "Oman"},
                            new CountryDTO() {Iso2 = "PK", Iso3 = "PAK", Name = "Pakistan"},
                            new CountryDTO() {Iso2 = "PW", Iso3 = "PLW", Name = "Palau"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Palmyra Atoll"},
                            new CountryDTO() {Iso2 = "PA", Iso3 = "PAN", Name = "Panama"},
                            new CountryDTO() {Iso2 = "PG", Iso3 = "PNG", Name = "Papua New Guinea"},
                            new CountryDTO() {Iso2 = "PY", Iso3 = "PRY", Name = "Paraguay"},
                            new CountryDTO() {Iso2 = "PE", Iso3 = "PER", Name = "Peru"},
                            new CountryDTO() {Iso2 = "AQ", Iso3 = "ATA", Name = "Peter I Island"},
                            new CountryDTO() {Iso2 = "PH", Iso3 = "PHL", Name = "Philippines"},
                            new CountryDTO() {Iso2 = "PN", Iso3 = "PCN", Name = "Pitcairn Islands"},
                            new CountryDTO() {Iso2 = "PL", Iso3 = "POL", Name = "Poland"},
                            new CountryDTO() {Iso2 = "PT", Iso3 = "PRT", Name = "Portugal"},
                            new CountryDTO() {Iso2 = "MD", Iso3 = "MDA", Name = "Pridnestrovie (Transnistria)"},
                            new CountryDTO() {Iso2 = "PR", Iso3 = "PRI", Name = "Puerto Rico"},
                            new CountryDTO() {Iso2 = "QA", Iso3 = "QAT", Name = "Qatar"},
                            new CountryDTO() {Iso2 = "AQ", Iso3 = "ATA", Name = "Queen Maud Land"},
                            new CountryDTO() {Iso2 = "RE", Iso3 = "REU", Name = "Reunion"},
                            new CountryDTO() {Iso2 = "RO", Iso3 = "ROU", Name = "Romania"},
                            new CountryDTO() {Iso2 = "AQ", Iso3 = "ATA", Name = "Ross Dependency"},
                            new CountryDTO() {Iso2 = "RU", Iso3 = "RUS", Name = "Russia"},
                            new CountryDTO() {Iso2 = "RW", Iso3 = "RWA", Name = "Rwanda"},
                            new CountryDTO() {Iso2 = "GP", Iso3 = "GLP", Name = "Saint Barthelemy"},
                            new CountryDTO() {Iso2 = "SH", Iso3 = "SHN", Name = "Saint Helena"},
                            new CountryDTO() {Iso2 = "KN", Iso3 = "KNA", Name = "Saint Kitts and Nevis"},
                            new CountryDTO() {Iso2 = "LC", Iso3 = "LCA", Name = "Saint Lucia"},
                            new CountryDTO() {Iso2 = "GP", Iso3 = "GLP", Name = "Saint Martin"},
                            new CountryDTO() {Iso2 = "PM", Iso3 = "SPM", Name = "Saint Pierre and Miquelon"},
                            new CountryDTO() {Iso2 = "VC", Iso3 = "VCT", Name = "Saint Vincent and the Grenadines"},
                            new CountryDTO() {Iso2 = "WS", Iso3 = "WSM", Name = "Samoa"},
                            new CountryDTO() {Iso2 = "SM", Iso3 = "SMR", Name = "San Marino"},
                            new CountryDTO() {Iso2 = "ST", Iso3 = "STP", Name = "Sao Tome and Principe"},
                            new CountryDTO() {Iso2 = "SA", Iso3 = "SAU", Name = "Saudi Arabia"},
                            new CountryDTO() {Iso2 = "SN", Iso3 = "SEN", Name = "Senegal"},
                            new CountryDTO() {Iso2 = "RS", Iso3 = "SRB", Name = "Serbia"},
                            new CountryDTO() {Iso2 = "SC", Iso3 = "SYC", Name = "Seychelles"},
                            new CountryDTO() {Iso2 = "SL", Iso3 = "SLE", Name = "Sierra Leone"},
                            new CountryDTO() {Iso2 = "SG", Iso3 = "SGP", Name = "Singapore"},
                            new CountryDTO() {Iso2 = "SK", Iso3 = "SVK", Name = "Slovakia"},
                            new CountryDTO() {Iso2 = "SI", Iso3 = "SVN", Name = "Slovenia"},
                            new CountryDTO() {Iso2 = "SB", Iso3 = "SLB", Name = "Solomon Islands"},
                            new CountryDTO() {Iso2 = "SO", Iso3 = "SOM", Name = "Somalia"},
                            new CountryDTO() {Iso2 = "SO", Iso3 = "SOM", Name = "Somaliland"},
                            new CountryDTO() {Iso2 = "ZA", Iso3 = "ZAF", Name = "South Africa"},
                            new CountryDTO()
                                {
                                    Iso2 = "GS",
                                    Iso3 = "SGS",
                                    Name = "South Georgia & South Sandwich Islands"
                                },
                            new CountryDTO() {Iso2 = "GE", Iso3 = "GEO", Name = "South Ossetia"},
                            new CountryDTO() {Iso2 = "ES", Iso3 = "ESP", Name = "Spain"},
                            new CountryDTO() {Iso2 = "LK", Iso3 = "LKA", Name = "Sri Lanka"},
                            new CountryDTO() {Iso2 = "SD", Iso3 = "SDN", Name = "Sudan"},
                            new CountryDTO() {Iso2 = "SR", Iso3 = "SUR", Name = "Suriname"},
                            new CountryDTO() {Iso2 = "SJ", Iso3 = "SJM", Name = "Svalbard"},
                            new CountryDTO() {Iso2 = "SZ", Iso3 = "SWZ", Name = "Swaziland"},
                            new CountryDTO() {Iso2 = "SE", Iso3 = "SWE", Name = "Sweden"},
                            new CountryDTO() {Iso2 = "CH", Iso3 = "CHE", Name = "Switzerland"},
                            new CountryDTO() {Iso2 = "SY", Iso3 = "SYR", Name = "Syria"},
                            new CountryDTO() {Iso2 = "TJ", Iso3 = "TJK", Name = "Tajikistan"},
                            new CountryDTO() {Iso2 = "TZ", Iso3 = "TZA", Name = "Tanzania"},
                            new CountryDTO() {Iso2 = "TH", Iso3 = "THA", Name = "Thailand"},
                            new CountryDTO() {Iso2 = "TL", Iso3 = "TLS", Name = "Timor-Leste (East Timor)"},
                            new CountryDTO() {Iso2 = "TG", Iso3 = "TGO", Name = "Togo"},
                            new CountryDTO() {Iso2 = "TK", Iso3 = "TKL", Name = "Tokelau"},
                            new CountryDTO() {Iso2 = "TO", Iso3 = "TON", Name = "Tonga"},
                            new CountryDTO() {Iso2 = "TT", Iso3 = "TTO", Name = "Trinidad and Tobago"},
                            new CountryDTO() {Iso2 = "TA", Iso3 = "TAA", Name = "Tristan da Cunha"},
                            new CountryDTO() {Iso2 = "TN", Iso3 = "TUN", Name = "Tunisia"},
                            new CountryDTO() {Iso2 = "TR", Iso3 = "TUR", Name = "Turkey"},
                            new CountryDTO() {Iso2 = "TM", Iso3 = "TKM", Name = "Turkmenistan"},
                            new CountryDTO() {Iso2 = "TC", Iso3 = "TCA", Name = "Turks and Caicos Islands"},
                            new CountryDTO() {Iso2 = "TV", Iso3 = "TUV", Name = "Tuvalu"},
                            new CountryDTO() {Iso2 = "VI", Iso3 = "VIR", Name = "U.S. Virgin Islands"},
                            new CountryDTO() {Iso2 = "UG", Iso3 = "UGA", Name = "Uganda"},
                            new CountryDTO() {Iso2 = "UA", Iso3 = "UKR", Name = "Ukraine"},
                            new CountryDTO() {Iso2 = "AE", Iso3 = "ARE", Name = "United Arab Emirates"},
                            new CountryDTO() {Iso2 = "GB", Iso3 = "GBR", Name = "United Kingdom"},
                            new CountryDTO() {Iso2 = "UY", Iso3 = "URY", Name = "Uruguay"},
                            new CountryDTO() {Iso2 = "UZ", Iso3 = "UZB", Name = "Uzbekistan"},
                            new CountryDTO() {Iso2 = "VU", Iso3 = "VUT", Name = "Vanuatu"},
                            new CountryDTO() {Iso2 = "VA", Iso3 = "VAT", Name = "Vatican City"},
                            new CountryDTO() {Iso2 = "VE", Iso3 = "VEN", Name = "Venezuela"},
                            new CountryDTO() {Iso2 = "VN", Iso3 = "VNM", Name = "Vietnam"},
                            new CountryDTO() {Iso2 = "UM", Iso3 = "UMI", Name = "Wake Island"},
                            new CountryDTO() {Iso2 = "WF", Iso3 = "WLF", Name = "Wallis and Futuna"},
                            new CountryDTO() {Iso2 = "YE", Iso3 = "YEM", Name = "Yemen"},
                            new CountryDTO() {Iso2 = "ZM", Iso3 = "ZMB", Name = "Zambia"},
                            new CountryDTO() {Iso2 = "ZW", Iso3 = "ZWE", Name = "Zimbabwe"},
                        };
            return c;
        }
    }
}


        