//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.DonationAddresses = new HashSet<DonationAddress>();
            this.DonationFundAllocations = new HashSet<DonationFundAllocation>();
        }
    
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public string AuthorizationNumber { get; set; }
        public string Last4ofCC { get; set; }
        public string MotivationCode { get; set; }
        public string SourceCode { get; set; }
        public Enum_ChargeStatus Status { get; set; }
        public string Notes { get; set; }
        public Enum_CardBrand CardBrand { get; set; }
        public Enum_PaymentMethod PaymentMethod { get; set; }
        public string GatewayName { get; set; }
        public string GatewayTransDetails { get; set; }
        public string TransactionId { get; set; }
        public bool TestMode { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual ICollection<DonationAddress> DonationAddresses { get; set; }
        public virtual ICollection<DonationFundAllocation> DonationFundAllocations { get; set; }
    }
}
