//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocos
{
    using System;
    
    public enum Enum_AddressType : short
    {
        Shipping = 1,
        Billing = 2,
        Technical = 3,
        Contact = 4
    }
}
