//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocos
{
    using System;
    
    public enum Enum_PaymentStatus : short
    {
        Paid = 1,
        UnPaid = 2,
        Failed = 3,
        Pending = 4
    }
}
