//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocos
{
    using System;
    
    public enum Enum_ChargeStatus : short
    {
        Approved = 1,
        Declined = 2,
        Voided = 3,
        Refunded = 4,
        Error = 5
    }
}
