//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocos
{
    using System;
    using System.Collections.Generic;

    public partial class Fund
    {
        public Fund()
        {
            this.IsDeleted = false;
            this.Active = true;
            this.SortOrder = 0;
            this.DonationFundAllocations = new HashSet<DonationFundAllocation>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long OrganizationId { get; set; }
        public bool IsDeleted { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public short SortOrder { get; set; }

        public virtual ICollection<DonationFundAllocation> DonationFundAllocations { get; set; }
    }
}
